version: '3.9'

services:
  eureka-service:
    container_name: els-container
    #build: # "context" and "dockerfile" fields have to be under "build"
      #context: ./
      #dockerfile: ./eureka-service/Dockerfile
    image: thakurpriyanka262/eureka-service
    #image: thakurpriyanka262/eureka-service.jar
    #build: ./eureka-service
    tty: true
    
    ports:
      - "8761:8761"
    
    restart: always
    
  #new service (java_app)
  user-service:
    container_name: user-service-container
    #build the docker image, same as docker build
    image: thakurpriyanka262/user-service
    #build: ./user-service
    ports:
      - 6969:6969
      
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-service:8761/eureka
      #- JAVA_OPTS=
        #-DEUREKA_SERVER=http://eureka-service:8761/eureka
      - DATABASE_URL=jdbc:postgresql://postgres-service:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - postgres-service
      - eureka-service

  #old service (postgres)
  postgres-service:
    container_name: postgres-container
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}

